"""
Set up sampling planes for AMR-Wind to use for inflow winds.
"""

from pyFAST.fastfarm.AMRWindSimulation import AMRWindSimulation

def main():
    # -----------------------------------------------------------------------------
    # USER INPUT: Modify these
    # -----------------------------------------------------------------------------

    # ----------- Wind farm
    wts  = {
            0 :{'x':1280.0,     'y':2560,       'z':0.0,  'D':126.9,  'zhub':86.5, 'cmax':5, 'fmax':10/6, 'Cmeander':1.9, 'name':'T0'},
            1 :{'x':1280.0,     'y':3200,       'z':0.0,  'D':126.9,  'zhub':86.5, 'cmax':5, 'fmax':10/6, 'Cmeander':1.9, 'name':'T1'},
            2 :{'x':1280.0,     'y':3840,       'z':0.0,  'D':126.9,  'zhub':86.5, 'cmax':5, 'fmax':10/6, 'Cmeander':1.9, 'name':'T2'},
            }

    # ----------- AMR-Wind parameters
    fixed_dt = 0.25
    prob_lo = (0.0, 0.0, 0.0)
    prob_hi = (2560.0, 6400.0, 1280.0)
    n_cell = (256, 640, 128)
    max_level = 1  # Number of grid refinement levels

    incflo_velocity_hh = (0.0, 10.0, 0.0)  # Hub-height velocity
    postproc_name = 'sampling'

    # ----------- I/O
    outdir = '/Users/orybchuk/Research/OpenFAST-python-toolbox'

    # -----------------------------------------------------------------------------
    # END OF USER INPUT
    # -----------------------------------------------------------------------------

    # Initial setup
    amr = AMRWindSimulation(wts, fixed_dt, prob_lo, prob_hi,
                           n_cell, max_level, incflo_velocity_hh,
                           postproc_name)

    # Write out sampling parameters
    amr.write_sampling_params(outdir)

    '''
    Below are the generated contents of sampling_config.i:
        # Sampling info generated by AMRWindSamplingCreation.py
        incflo.post_processing = sampling # averaging
        sampling.output_frequency = 1
        sampling.fields = velocity # temperature tke
        sampling.labels = Low HighT0_inflow0deg HighT1_inflow0deg HighT2_inflow0deg

        # Low sampling grid spacing = 10.0 m
        sampling.Low.type         = PlaneSampler
        sampling.Low.num_points   = 78 206
        sampling.Low.origin       = 885.0 2165.0 5.0
        sampling.Low.axis1        = 770.0 0.0 0.0
        sampling.Low.axis2        = 0.0 2050.0 0.0
        sampling.Low.normal       = 0.0 0.0 1.0
        sampling.Low.offsets      = 0 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270 280

        # Turbine T0 at (x,y) = (1280.0, 2560), with D = 126.9, grid spacing = 5.0 m
        sampling.HighT0_inflow0deg.type         = PlaneSampler
        sampling.HighT0_inflow0deg.num_points   = 32 32
        sampling.HighT0_inflow0deg.origin       = 1197.5 2477.5 2.5
        sampling.HighT0_inflow0deg.axis1        = 155.0 0.0 0.0
        sampling.HighT0_inflow0deg.axis2        = 0.0 155.0 0.0
        sampling.HighT0_inflow0deg.normal       = 0.0 0.0 1.0
        sampling.HighT0_inflow0deg.offsets      = 0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225 230

        # Turbine T1 at (x,y) = (1280.0, 3200), with D = 126.9, grid spacing = 5.0 m
        sampling.HighT1_inflow0deg.type         = PlaneSampler
        sampling.HighT1_inflow0deg.num_points   = 32 32
        sampling.HighT1_inflow0deg.origin       = 1197.5 3117.5 2.5
        sampling.HighT1_inflow0deg.axis1        = 155.0 0.0 0.0
        sampling.HighT1_inflow0deg.axis2        = 0.0 155.0 0.0
        sampling.HighT1_inflow0deg.normal       = 0.0 0.0 1.0
        sampling.HighT1_inflow0deg.offsets      = 0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225 230

        # Turbine T2 at (x,y) = (1280.0, 3840), with D = 126.9, grid spacing = 5.0 m
        sampling.HighT2_inflow0deg.type         = PlaneSampler
        sampling.HighT2_inflow0deg.num_points   = 32 32
        sampling.HighT2_inflow0deg.origin       = 1197.5 3757.5 2.5
        sampling.HighT2_inflow0deg.axis1        = 155.0 0.0 0.0
        sampling.HighT2_inflow0deg.axis2        = 0.0 155.0 0.0
        sampling.HighT2_inflow0deg.normal       = 0.0 0.0 1.0
        sampling.HighT2_inflow0deg.offsets      = 0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225 230
    '''

if __name__ == '__main__':
    main()